on:
  push:
    branches:
      - main
      - develop
  pull_request_review:
    paths-ignore:
      - '**.md'
      - '.vscode/**.json'

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm lint
